#
#  Author: Hari Sekhon
#  Date: 2019-11-28 18:51:59 +0000 (Thu, 28 Nov 2019)
#
#  https://github.com/harisekhon/devops-perl-tools
#
#  License: see accompanying Hari Sekhon LICENSE file
#
#  If you're using my code you're welcome to connect with me on LinkedIn
#  and optionally send me feedback to help improve or steer this or other code I publish
#
#  https://www.linkedin.com/in/harisekhon
#

apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: NAME-schedule
spec:
  schedule: "0 0 * * *"
  startingDeadlineSeconds: 3600  # (re)start up to an hour late
  concurrencyPolicy: Forbid  # Allow / Forbid / Replace - start new job if old job is still running (default: Allow, in which case your jobs should be idempotent)
  suspend: False  # set to True to prevent new job executions (counted as missed jobs)
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      metadata:
        name: NAME
      spec:
        containers:
        - name: NAME
          image: perl
          # takes about a minute to execute
          command: ["perl"]
          args: ["-Mbignum=bpi", "-wle", "print bpi(2000)"]
        restartPolicy: Never
